### ISSUE TITLE
update the datalad module

### ISSUE THREAD

**Issue by pbellec** [brainhackorg/school#107]
located here: https://school.brainhackmtl.org/modules/datalad/

I have contacted Adina to see if there would be more recent resources we could use.

**Comment by adswa** [comment]
hey, sorry for the late reply! I checked if I have anything as concise and general as the one from OHBM 2020, and either its longer or on some specialized topic. If longer is not a problem, the playlist  @complexbrains linked is indeed the best and most up to date - just sadly long. Otherwise, until when do you need it? I will create new material for Neurohackedemy in the coming 2 weeks that should be concise and up to date. I can share this if it fits your time frame?

**Comment by pbellec** [comment]
we'll make sure to incorporate the updated material for next year's brainhack school :) 

Piggybacking neurohackademy is truly what we do, so we're fine with the lag.

**Comment by complexbrains** [comment]
I will update the resources with these tutorials then. Thank you @adswa 🤗
